StoreApp/Models/RepositoryContext.cs
using Microsoft.EntityFrameworkCore;

namespace StoreApp.Models
{
    public class RepositoryContext : DbContext
    {
        public DbSet<Product> Products { get; set; }

        public RepositoryContext(DbContextOptions<RepositoryContext> options) : base(options)
        {

        }
        //Baslangicta databasein verilerinin bos olmamasi icin default veri tanimlamari yapilacak
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);
            modelBuilder.Entity<Product>()
                .HasData(
                    new Product() { ProductId = 1, ProductName = "Computer", Price = 17_000 },
                    new Product() { ProductId = 2, ProductName = "KeyBoard", Price = 7_000 },
                    new Product() { ProductId = 3, ProductName = "Mouse", Price = 1_000 },
                    new Product() { ProductId = 4, ProductName = "Speaker", Price = 5_000 },
                    new Product() { ProductId = 5, ProductName = "Microphone", Price = 1_000 }
                );
        }
        ///cmdde yazilan kodlar:
        //dotnet ef migrations add init sqlin olusmasi icin ilgili scriptleri hazirliyor
        //dotnet ef migrations add ProductSeedData sqlde guncelleme yapildiysa ilgili scriptleri haziyliyor
        //dotnet ef database update scriptlere gore sqli guncelliyor

    }
}

StoreApp/Areas/Admin/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;

namespace StoreApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

StoreApp/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace StoreApp.Areas.Admin.AddControllersWithViews
{
    [Area("Admin")]
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

StoreApp/Areas/Admin/Controllers/ProductController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductController : Controller
    {
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            var model = _manager.ProductService.GetAllProducts(false);
            return View(model);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([FromForm] Product product)
        {
            //_manager.ProductService.CreateProduct(product);
            return RedirectToAction("Index");
            //var model = _manager.ProductService.GetAllProducts(false);
            //return View("Index", model);
        }
    }
}

StoreApp/Components/CategoriesMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Services.Contracts;

namespace StoreApp.Components
{
    public class CategoriesMenuViewComponent : ViewComponent
    {
        private readonly IServiceManager _manager;

        public CategoriesMenuViewComponent(IServiceManager manager)
        {
            _manager = manager;
        }

        public IViewComponentResult Invoke()
        {
            var categories = _manager.CategoryService.GetAllCategories(false);
            return View(categories);
        }
    }
}

StoreApp/Components/ProductSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Repositories;
using Services.Contracts;

namespace StoreApp.Components
{
    public class ProductSummaryViewComponent : ViewComponent
    {
        //Direkt repositoryden ulasmak yerine artik serviceleri kullanmak daha saglikli
        private readonly IServiceManager _manager;

        public ProductSummaryViewComponent(IServiceManager manager)
        {
            _manager = manager;
        }


        public string Invoke()
        {
            return _manager.ProductService.GetAllProducts(false).Count().ToString();
        }
    }
}

StoreApp/Controllers/CategoryController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Repositories.Contracts;

namespace StoreApp.Controllers
{
    public class CategoryController : Controller
    {
        private IRepositoryManager _manager;

        public CategoryController(IRepositoryManager manager)
        {
            _manager = manager;
        }

        public IActionResult Index()
        {
            var model = _manager.Category.FindAll(false);
            return View(model);
        }
    }
}

StoreApp/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace StoreApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
    
}

StoreApp/Controllers/ProductController.cs
using Entities.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Repositories;
using Repositories.Contracts;
using Services.Contracts;

namespace StoreApp.Controllers
{
    public class ProductController : Controller
    {
        #region DI
        //This pattern is Dipendancy Injection Pattern,
        //When we created repository services on program.cs this will automatically used
        //instead of using commended context section below


        //Eskiden sadece dbContext varken bu kullaniliyordu, artik repomanager sistemine gectigimiz icin buna gerek yok
        //private readonly RepositoryContext _context;
        private readonly IServiceManager _manager;

        public ProductController(IServiceManager manager)
        {
            _manager = manager;
        }



        #endregion
        public IActionResult Index()
        {
            /*
            var context = new RepositoryContext(
                new DbContextOptionsBuilder<RepositoryContext>()
                .UseSqlite("Data Source = C:\\sqlite3\\MVC\\ProductDb.db").Options);
                */
            // return _context.Products;
            //var model = _context.Products.ToList();

            var model = _manager.ProductService.GetAllProducts(false);
            return View(model);
        }

        public IActionResult Get([FromRoute(Name = "id")] int id)
        {
            // Product product = _context.Products.First(p => p.ProductId.Equals(id));
            //return View(product);
            var model = _manager.ProductService.GetOneProduct(id, false);
            return View(model);
        }
    }
}

StoreApp/Areas/Admin/Views/Category/Index.cshtml
<h3>Category Index</h3>
@section Footer{
 Emre Adamdir
 } 

StoreApp/Areas/Admin/Views/Dashboard/Index.cshtml
<h4>Dashboard Index</h4>

StoreApp/Areas/Admin/Views/Product/Create.cshtml
@model Product
<div
  class="text-center"
  style="max-width: 70%; align-self: center; margin: auto"
>
  <div class="display-6">EE OLURRRR</div>

  <form method="post" asp-action="Create">
    <div class="form-group my-3">
      <label asp-for="ProductName"></label>
      <input
        asp-for="ProductName"
        class="form-control"
        type="text"
        placeholder="Enter a Product Name"
      />
    </div>
    <div class="form-group my-3">
      <label asp-for="Price"></label>
      <input
        asp-for="Price"
        class="form-control"
        type="text"
        placeholder="Enter a Price"
      />
    </div>
    <div class="form-group my-3">
        <div class="">
      <button class="btn btn-primary mx-3" type="submit">
        <i class="fa fa-save"></i>
        Save
      </button>
      <a asp-action="Index" class="btn btn-outline-warning mx-3" >
        <i class="fa fa-cancel"></i>
        Back</a>
      </div>
    </div>
  </form>
</div>

StoreApp/Areas/Admin/Views/Product/Index.cshtml
@model IEnumerable<Product>

<div class="text-center">
  <div class="display-6">Products</div>

  <div class="d-flex justify-content-end my-3">
    <a asp-action="Create" class="btn btn-outline-success">
      <i class="fa fa-plus"></i>
      Create</a>
  </div>

  <table class="table table-striped table-hover">
    <thead>
      <tr>
        <th>Id</th>
        <th>Product Name</th>
        <th>Price</th>
        <th>Operations</th>
      </tr>
    </thead>
    <tbody>
      @foreach (Product item in Model)
      {
        <tr>
          <td>@item.ProductId</td>
          <td>@item.ProductName</td>
          <td>@item.Price</td>
          <td></td>
        </tr>
      }
    </tbody>
  </table>
</div>

StoreApp/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/lib/font-awesome/css/all.css"/>
    <title>Document</title>
</head>
<body>
    <header>
        <partial name="_Navbar"/>
        @RenderSection("Header",false)
    </header>
    <div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
    </div>
    <footer>
        Footer
        @RenderSection("Footer",false)

    </footer>
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    <script src="~/js/site.js"></script>
    @await RenderSectionAsync("Scripts",false)
</body>
</html>

StoreApp/Areas/Admin/Views/Shared/_Navbar.cshtml
<nav class="navbar bg-dark border-bottom navbar-expand-lg ">
  <div class="container-fluid">
    <a class="navbar-brand text-white" href="/Admin">ADMIN</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse d-sm-inline-flex justfiy-content-between" id="navbarNavAltMarkup">
        <ul class="navbar-nav flex-grow-1">
          <li class="nav-item">
            <a class="nav-link text-white" aria-current="page" asp-controller="Dashboard" asp-action="Index">Dashboard</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" aria-current="page" asp-controller="Product" asp-action="Index">Products(@await Component.InvokeAsync("ProductSummary"))</a>
          </li>
          <li class="nav-item">
            <a class="nav-link text-white" aria-current="page" asp-controller="Category" asp-action="Index">Categories</a>
          </li>
        </ul>
      <ul class="navbar-nav text-white">
            <a class="nav-link text-white" target="_blank" aria-current="page" asp-area="" asp-controller="Home" asp-action="Index">Web</a>
        
      </ul>
    </div>
  </div>
</nav>

StoreApp/Views/Category/Index.cshtml
@model IEnumerable<Category>

    <ul class="list-group">
        @foreach (var cat in Model)
        {
            <li class="list-group-item">@cat.CategoryName</li>
        }
    </ul>

StoreApp/Views/Home/Index.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Hello Store App</h1>
</body>
</html>

StoreApp/Views/Product/Get.cshtml
@model Product

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h3>@Model.ProductName</h3>
    <p>@Model.Price</p>
    <div class="btn-group">
        <a class="btn btn-primary" asp-action="Index" asp-controller="Home">
            <i class="fa-solid fa-house"></i>
            Home</a>
        <a class="btn btn-outline-primary " asp-action="Index" asp-controller="Product">
            <i class="fa-solid fa-list"></i>
            Products</a>
    </div>
</body>
</html>

StoreApp/Views/Product/Index.cshtml
@* //how to use layout parts *@
@* @section Footer{
    <div>
        Only For Index Footer
    </div>
}
 *@
@model IQueryable<Product>   
    <div class="row">
<div class="col-md-3">
    @await Component.InvokeAsync("CategoriesMenu")  @*ViewComponent yapisi *@
</div>
        <div class="col-md-9">
            <div class="row my-3">
        @foreach (Product prd in Model)
        {
            <partial name="_ProductCard" model="@prd"/>
        }
            </div>
        </div>
    

StoreApp/Views/Product/_ProductCard.cshtml
@model Product


            <div class="col-sm-12 col-md-6 col-lg-4  my-2">
                
            <div class="card" style="width: 18rem;">
  <img src="/images/berker.jpg" class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">@Model.ProductName</h5>
    <p class="card-text">@Model.Price.ToString("c")</p>
    <a class="btn btn-primary" asp-action="Get" asp-route-id="@Model.ProductId">
                        <i class="fa-solid fa-arrow-right"></i>
                        Get Details</a>
  </div>
</div>
            </div>

StoreApp/Views/Shared/Components/CategoriesMenu/Default.cshtml
@model IEnumerable<Category>
<div class="my-4">
  <ul class="list-group">
        @foreach (var cat in Model)
        {
        <li class="list-group-item">@cat.CategoryName</li>
        }
  </ul>
</div>

StoreApp/Views/Shared/_Navbar.cshtml
<nav class="navbar bg-light border-bottom navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Store App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-link active" aria-current="page" asp-controller="home" aps-action="Index">Home</a>
        <a class="nav-link" aria-current="page" asp-controller="Product" aps-action="Index">Products(@await Component.InvokeAsync("ProductSummary"))</a>
        <a class="nav-link" aria-current="page" asp-controller="Category" aps-action="Index">Categories</a>

      </div>
    </div>
  </div>
</nav>